name: Build for windows
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - chore/*
      - security/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  ZLIB_COMMIT: 09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851
  ZSTD_COMMIT: 794ea1b0afca0f020f4e57b6732332231fb23c70
  BROTLI_COMMIT: ed738e842d2fbdf2d6459e39267a633c4a9b2f5d
  BORINGSSL_COMMIT: 673e61fc215b178a90c0e67858bbf162c8158993
  CURL_TAG: curl-8_15_0  # using tags is less secure, but easier to maintain
  NGHTTP2_COMMIT: 8f44147c385fb1ed93a6f39911eeb30279bfd2dd
  NGHTTP3_TAG: v1.15.0
  NGTCP2_TAG: v1.20.0

jobs:
  build-windows:
    name: Build windows binaries
    runs-on: windows-latest
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install NASM
        shell: cmd
        run: choco install nasm -y

      - name: Fetch and patch deps
        shell: bash
        run: ./win/deps.sh

      # - name: Setup tmate session for debugging
      #   uses: mxschmitt/action-tmate@v3

      - name: Build
        shell: cmd
        run: ./win/build.bat vcvars64
        env:
          DISABLE_ASM_ARM64: false

      - name: Build tarball
        shell: bash
        run: |
          NAME=${{ github.ref_name }}
          if [ -z "$NAME" ]; then
            NAME=dev
          fi

          tar cvzf libcurl-impersonate-${NAME}.x86_64-win32.tar.gz -C ./packages .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts.windows.x86_64
          path: ./libcurl-impersonate*.tar.gz
